### ISSUE TITLE
"Prologue" mission Disabled unit error message

### ISSUE THREAD

**Issue by DarkianMaker** [Kromster80/knights_province#191]
Issue:
Playing the Prologue mission of the Orthalm campaign starts with an error saying the unit type Recruit has been disabled. The mission can be played after closing the error message.

Cause:
Recruits are disabled but haven't been removed from the campaign mission.

Solution:
Updating the mission by removing Recruits and replacing them with other units to man the towers. (This will have to be combined with the pending update to fix the mission objectives).

**Comment by DarkianMaker** [comment]
This issue has been resolved a while ago actually, but now the recruits have also been replaced with archers so it is now fully fixed with no AI oddities going on.

**Comment by Kromster80** [comment]
The error still manifests:

![image](https://user-images.githubusercontent.com/4618474/78106290-665f7300-73f3-11ea-9ad5-ac8f463196a2.png)

**Comment by Kromster80** [comment]
Fixed it in Alpha 11 best way I could
